# This is the configuration file for PlatformIO, a cross-platform tool and IDE
# to build and develop software for embedded systems.
#
# To build the firmware with PlatformIO, install PlatformIO Core (CLI, no GUI):
# - https://docs.platformio.org/en/latest//core/installation.html
#
# For documentation on this file, see:
# - https://docs.platformio.org/en/latest/projectconf/index.html
#
# To add support for another STM32H7xx board, add a new [env:name..] section
# with the appropriate `board` and (optionally) `board_build.ldscript`.
# For a list of supported hardware, see:
# - https://docs.platformio.org/en/latest/platforms/ststm32.html
#
# To add support for additional grblHAL plugins or drivers, the necessary changes
# can be made to any of the following sections (see examples below);
# - common settings, which will apply to all builds
# - feature specific settings that can be included per board
# - board specific settings
#
# By default this file sets the preprocessor directive `OVERRIDE_MY_MACHINE`
# to ignore all settings in `Inc/my_machine.h`.  Instead, you should edit this
# file and add the necessary directives (e.g. `-D FOOBAR_ENABLE`) to either
# `common.build_flags` or the environment specific `build_flags`.
#
# Typical command line usage:
#
#    # Build firmware for all defined environments
#    pio run
#    # Build only for specific environments with the -e option
#    pio run -e nucleo_h743_reference
#    # List the freshly built firmware ELF (.elf) and binary (.bin) files:
#    ls -l .pio/build/*/firmware.*
#    # If the target supports uploading (via `upload_protocol`):
#    pio run -e nucleo_h743_reference -t upload
#    # Clean up build related resources
#    pio run -t clean
#

[platformio]
include_dir = Inc
src_dir = Src

# Common build settings that apply to all environments, see my_machine.h for examples
[common]
build_flags =
  -I .
  -I boards
  # Enable L1 cache and assocatied cache maintenance functions
  -D L1_CACHE_ENABLE=1
  # Ignore all settings in Inc/my_machine.h (and instead use the below build flags)
  -D OVERRIDE_MY_MACHINE
  # Enable floating point support for printf/scanf
  -Wl,-u,_printf_float
  -Wl,-u,_scanf_float
  # Run ISR code from ITCM RAM
 '-D ISR_CODE=__attribute__((section(".itcmram")))'
  # Uncomment to enable debug builds
  #-D DEBUG
lib_deps =
  grbl
  boards
  plugins
  #bluetooth
  #keypad
  #laser
  #motors
  #trinamic
  #odometer
  #spindle
lib_extra_dirs =
  .

[common_h723]
lib_deps = Startup723
           ${common.lib_deps}

# Build settings for SD card support, include in board environments as needed
[sdcard]
build_flags =
  -D SDCARD_ENABLE=1
  -I Middlewares/Third_Party/FatFs/src
  -I FATFS/Target
  -I FATFS/App
lib_deps =
  sdcard
  FATFS/App
  FATFS/Target
  Middlewares/Third_Party/FatFs
lib_extra_dirs =

# Build settings for H723 USB serial support, include in board environments as needed
# (STM32H723xx does not have a FS USB peripherial, using the HS peripheral in FS mode)
[usb_h723]
build_flags =
  -D USB_SERIAL_CDC=1
  -I Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
  -I Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I USB_DEVICE_H723/Target
  -I USB_DEVICE_H723/App
lib_deps =
  USB_DEVICE_H723/App
  USB_DEVICE_H723/Target
  Middlewares/ST/STM32_USB_Device_Library/Class
  Middlewares/ST/STM32_USB_Device_Library/Core
lib_extra_dirs =


[env]
platform = ststm32
platform_packages = framework-stm32cubeh7 @ 1.12.1
framework = stm32cube
# Do not produce .a files for lib deps (which would prevent them from overriding weak symbols)
lib_archive = no
lib_ldf_mode = off

# BTT Octopus Pro v1.1 (H723) with USB serial and Trinamic 2209 driver support -- 128K bootloader
[env:btt_octopus_pro_h723_tmc2209_bl128]
board = generic_stm32h723ze
board_build.ldscript = STM32H723ZETX_FLASH_BL.ld
build_flags = ${common.build_flags}
              ${sdcard.build_flags}
              ${usb_h723.build_flags}
  # See Inc/my_machine.h for options
  -D BOARD_BTT_OCTOPUS_PRO
  ; -D USE_HAL_DRIVER
  ; -D BLOCK_BUFFER_DYNAMIC
  -D STM32H723xx
  -D HSE_VALUE=25000000
  ; -D TRINAMIC_ENABLE=2209 # TODO enable only for z axis
  -D EEPROM_ENABLE=32

  # Ganged Y Axis
  -D Y_GANGED=1
  -D Y_AUTO_SQUARE=1
  -D Y_GANGED_LIM_MAX=1              # Use y limit switches together as max limit switches

  -D DEFAULT_STEPPER_DEENERGIZE_MASK=255      # Do not deenergize any steppers when idle
  -D DEFAULT_DIR_SIGNALS_INVERT_MASK="X_AXIS_BIT"   # Invert X-Axis direction

  # Axis steps per mm
  -D DEFAULT_X_STEPS_PER_MM="400.0f"
  -D DEFAULT_Y_STEPS_PER_MM="400.0f"
  -D DEFAULT_Z_STEPS_PER_MM="200.0f"

  # Travel
  -D DEFAULT_X_MAX_TRAVEL="195.0f"
  -D DEFAULT_Y_MAX_TRAVEL="345.0f"
  -D DEFAULT_Z_MAX_TRAVEL="65.0f"

  # Acceleration
  -D DEFAULT_X_ACCELERATION="100.0f" # mm/s² (150 also works but better be conservative)
  -D DEFAULT_Y_ACCELERATION="100.0f" # mm/s² (150 also works but better be conservative)
  -D DEFAULT_Z_ACCELERATION="10.0f" # mm/s²

  # Velocity
  -D DEFAULT_X_MAX_RATE="12000.0f" # = 200 mm/s
  -D DEFAULT_Y_MAX_RATE="12000.0f" # = 200 mm/s
  -D DEFAULT_Z_MAX_RATE="1000.0f" # = 200 mm/s

  -D DEFAULT_CONTROL_SIGNALS_INVERT_MASK=78   # 0000000001001110 (see config.h SIGNALS_BITMASK)

  # Limit switches
  -D DEFAULT_SOFT_LIMIT_ENABLE=1
  -D DEFAULT_HARD_LIMIT_ENABLE=1
  -D DEFAULT_CHECK_LIMITS_AT_INIT=1

  # Homing switches and Probe
  -D PROBE_ENABLE=0
  -D DEFAULT_HOMING_ENABLE=1                  # Enable homing
  -D DEFAULT_HOMING_USE_LIMIT_SWITCHES=1      # Use limit switches for homing
  -D DEFAULT_LIMIT_SIGNALS_PULLUP_DISABLE_MASK="X_AXIS_BIT" # Enable pull-down on X limit port (required for probe input)
  ; Had to be set in config.h because arithmetics dont work in build_flags:
  -D DEFAULT_HOMING_DIR_MASK=3   # Configure homing directions: (X_AXIS_BIT | Y_AXIS_BIT) = (1 | 2) = 3
  -D DEFAULT_LIMIT_SIGNALS_INVERT_MASK=3 # Normally open switches on X and Y: (X_AXIS_BIT | Y_AXIS_BIT) = (1 | 2) = 3
  -D DEFAULT_HOMING_CYCLE_0="Z_AXIS_BIT"
  -D DEFAULT_HOMING_CYCLE_1="X_AXIS_BIT"
  -D DEFAULT_HOMING_CYCLE_2="Y_AXIS_BIT"
  -D DEFAULT_HOMING_PULLOFF="1.0f"
  -D DEFAULT_HOMING_FORCE_SET_ORIGIN=1
  ; DEFAULT_HOMING_FEED_RATE
  ; DEFAULT_HOMING_SEEK_RATE
  ; DEFAULT_HOMING_PULLOFF
  -D DEFAULT_HOMING_SINGLE_AXIS_COMMANDS=1    # Allow homing single axis with `$HX`, `$HY`, `$HZ`
  -D DEFAULT_HOMING_INIT_LOCK=0               # Enforce homing after power up (WARNING: homing only one axis (`$HX`) is sufficient for HOMING_INIT_LOCK)
  -D DEFAULT_HOMING_OVERRIDE_LOCKS=0          # Allow resetting homing lock with soft reset (deactivated)
  -D DEFAULT_HOMING_ALLOW_MANUAL=0            # Allow manually setting home to current position (deactivated)

  -D MOTORS_ENABLE=1 # allow enabling and disabling stepper motors with M17 / M18 (TODO: not working??)

  # TODO: Backlash values for XYZ($160 - $162 have no compile time defaults (have to be set after every $RST operation!!))
  -D ENABLE_BACKLASH_COMPENSATION=1 

lib_deps = ${common_h723.lib_deps}
           ${usb_h723.lib_deps}
           ${sdcard.lib_deps}
           motors
           trinamic
           eeprom
lib_extra_dirs = ${common.lib_extra_dirs}
                 ${usb_h723.lib_extra_dirs}
                 ${sdcard.lib_extra_dirs}
upload_protocol = dfu


